name: Build & Tests
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    # Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer 
    container: node:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

