name: Build & Tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    # Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
    container: node:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install deps
        run: yarn # bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
